Capture Mode: Monitor
Monitor Index: 1
Window Title: ''
FPS: 60
Show FPS: true
Output Resolution: 1080
IPD: 0.064
Display Mode: Half-SBS
Model List:
  depth-anything/Depth-Anything-V2-Large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Depth-Anything-V2-Base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Depth-Anything-V2-Small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Video-Depth-Anything-Large:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Video-Depth-Anything-Base:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Video-Depth-Anything-Small:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  depth-anything/DA3-GIANT:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  depth-anything/DA3-LARGE:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  depth-anything/DA3-BASE:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  depth-anything/DA3-SMALL:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  depth-anything/DA3METRIC-LARGE:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  depth-anything/DA3MONO-LARGE:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  depth-anything/DA3NESTED-GIANT-LARGE:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  depth-anything/Depth-Anything-V2-Metric-Outdoor-Large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Depth-Anything-V2-Metric-Outdoor-Base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Depth-Anything-V2-Metric-Outdoor-Small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Depth-Anything-V2-Metric-Indoor-Large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Depth-Anything-V2-Metric-Indoor-Base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Depth-Anything-V2-Metric-Indoor-Small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Metric-Video-Depth-Anything-Large:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Metric-Video-Depth-Anything-Base:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/Metric-Video-Depth-Anything-Small:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/prompt-depth-anything-vitl-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/prompt-depth-anything-vits-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything/prompt-depth-anything-vits-transparent-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  LiheYoung/depth-anything-large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  LiheYoung/depth-anything-base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  LiheYoung/depth-anything-small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  xingyang1/Distill-Any-Depth-Large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  lc700x/Distill-Any-Depth-Base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  xingyang1/Distill-Any-Depth-Small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  lc700x/dpt-dinov2-giant-kitti-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  lc700x/dpt-dinov2-large-kitti-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  lc700x/dpt-dinov2-base-kitti-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  facebook/dpt-dinov2-small-kitti:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  facebook/dpt-dinov2-giant-nyu:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  lc700x/dpt-dinov2-large-nyu-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  lc700x/dpt-dinov2-base-nyu-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  lc700x/dpt-dinov2-small-nyu-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  lc700x/depth-ai-hf:
    resolutions:
    - 224
    - 192
  lc700x/dpt-hybrid-midas-hf:
    resolutions:
    - 384
  Intel/dpt-beit-base-384:
    resolutions:
    - 384
    - 336
    - 288
    - 240
    - 192
  Intel/dpt-beit-large-512:
    resolutions:
    - 512
    - 448
    - 384
    - 288
    - 192
  Intel/dpt-large:
    resolutions:
    - 384
    - 336
    - 288
    - 240
    - 192
  lc700x/dpt-large-redesign-hf:
    resolutions:
    - 384
    - 336
    - 288
    - 240
    - 192
  Intel/zoedepth-nyu-kitti:
    resolutions:
    - 384
    - 336
    - 288
    - 240
    - 192
  Intel/zoedepth-nyu:
    resolutions:
    - 384
    - 336
    - 288
    - 240
    - 192
  Intel/zoedepth-kitti:
    resolutions:
    - 384
    - 336
    - 288
    - 240
    - 192
  apple/DepthPro-hf:
    resolutions:
    - 1536
Depth Model: depth-anything/Depth-Anything-V2-Small-hf
Depth Strength: 2.0
Anti-aliasing: 2
Foreground Scale: 0.0
Depth Resolution: 336
FP16: true
Download Path: models
HF Endpoint: https://hf-mirror.com
Computing Device: 0
Language: EN
Run Mode: Local Viewer
Stream Protocol: HLS
Streamer Port: 1122
Stream Quality: 100
torch.compile: false
TensorRT: false
Recompile TensorRT: false
Unlock Thread (Legacy Streamer): false
Capture Tool: DXCamera
Fill 16:9: true
Fix Viewer Aspect: false
Stream Key: live
Stereo Mix: 立体声混音 (Realtek(R) Audio)
CRF: 20
Audio Delay: -0.15
Specify Display: false
Stereo Monitor: 1
